//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.COZINHEIRO = new HashSet<COZINHEIRO>();
            this.COMSUMIDOR = new HashSet<COMSUMIDOR>();
        }
    
        public int COD_CLIENTE { get; set; }
        public string NOME { get; set; }
        public int CPF { get; set; }
        public int RG { get; set; }
        public int TELEFONE { get; set; }
        public string CIDADE { get; set; }
        public string BAIRRO { get; set; }
        public string RUA { get; set; }
        public int NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COZINHEIRO> COZINHEIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMSUMIDOR> COMSUMIDOR { get; set; }
    }
}
