//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COZINHEIRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COZINHEIRO()
        {
            this.PEDIDO = new HashSet<PEDIDO>();
        }
    
        public int COD_COZINHEIRO { get; set; }
        public int COD_CLIENTE_FK { get; set; }
        public string CERTIFICACAO { get; set; }
        public string SENHA_COZ { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO> PEDIDO { get; set; }
    }
}
