//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModels : DbContext
    {
        public DBModels()
            : base("name=DBModels")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<COMSUMIDOR> COMSUMIDOR { get; set; }
        public virtual DbSet<COZINHEIRO> COZINHEIRO { get; set; }
        public virtual DbSet<HAMBURGUER> HAMBURGUER { get; set; }
        public virtual DbSet<HAMBURGUER_INGREDIENTE> HAMBURGUER_INGREDIENTE { get; set; }
        public virtual DbSet<INGREDIENTE> INGREDIENTE { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDO_HAMBURGUER> PEDIDO_HAMBURGUER { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public class InfoLogin
        {
            public CLIENTE CLIENTE { get; set; }
            public COMSUMIDOR COMSUMIDOR { get; set; }

            public COZINHEIRO COZINHEIRO { get; set; }

            public InfoLogin()
            {
                CLIENTE = new CLIENTE();
                COMSUMIDOR = new COMSUMIDOR();
                COZINHEIRO = new COZINHEIRO();
            }
        }
    }
}
