//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAMBURGUER_INGREDIENTE
    {
        public int COD_HAMBURGUER_INGREDIENTE { get; set; }
        public int COD_HAMBURGUER_FK { get; set; }
        public int COD_INGREDIENTE_FK { get; set; }
        public Nullable<int> QUANTIDADE { get; set; }
        public Nullable<double> PRECO_TOTAL_HAM_ING { get; set; }
    
        public virtual HAMBURGUER HAMBURGUER { get; set; }
        public virtual INGREDIENTE INGREDIENTE { get; set; }
    }
}
