//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAMBURGUER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HAMBURGUER()
        {
            this.HAMBURGUER_INGREDIENTE = new HashSet<HAMBURGUER_INGREDIENTE>();
            this.PEDIDO_HAMBURGUER = new HashSet<PEDIDO_HAMBURGUER>();
        }
    
        public int COD_HAMBURGUER { get; set; }
        public Nullable<double> PRECO_HAMBURGUER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAMBURGUER_INGREDIENTE> HAMBURGUER_INGREDIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_HAMBURGUER> PEDIDO_HAMBURGUER { get; set; }
    }
}
