//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGREDIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGREDIENTE()
        {
            this.HAMBURGUER_INGREDIENTE = new HashSet<HAMBURGUER_INGREDIENTE>();
        }
    
        public int COD_INGREDIENTE { get; set; }
        public string DESCR_INGREDIENTE { get; set; }
        public string TIPO_INGREDIENTE { get; set; }
        public double PRECO_INGREDIENTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAMBURGUER_INGREDIENTE> HAMBURGUER_INGREDIENTE { get; set; }
    }
}
