//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PEDIDO_HAMBURGUER = new HashSet<PEDIDO_HAMBURGUER>();
        }
    
        public int COD_PEDIDO { get; set; }
        public int COD_CONSUMIDOR_FK { get; set; }
        public Nullable<int> COD_COZINHEIRO_FK { get; set; }
        public Nullable<double> PRECO_PEDIDO { get; set; }
        public string STATUS { get; set; }
    
        public virtual COMSUMIDOR COMSUMIDOR { get; set; }
        public virtual COZINHEIRO COZINHEIRO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PEDIDO_HAMBURGUER> PEDIDO_HAMBURGUER { get; set; }
    }
}
