//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteHamburguer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_HAMBURGUER
    {
        public int COD_PEDIDO_HAMBURGUER { get; set; }
        public int COD_PEDIDO_FK { get; set; }
        public int COD_HAMBURGUER_FK { get; set; }
        public int QUANTIDADE_PED_HAM { get; set; }
        public double PRECO_TOTAL_PED_HAM { get; set; }
    
        public virtual HAMBURGUER HAMBURGUER { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
    }
}
